name: SBT CI

# Run SBT tests on pushes and pull requests to master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest
    # The specific container to use
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer
    # https://hub.docker.com/r/hseeberger/scala-sbt/
    container: hseeberger/scala-sbt:8u222_1.3.5_2.13.1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Run unit tests
      - name: Run Unit Tests
        run: sbt "clean;compile;test"

  assemble:
    # The type of runner that the job will run on
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest
    # The specific container to use
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer
    # https://hub.docker.com/r/hseeberger/scala-sbt/
    container: hseeberger/scala-sbt:8u222_1.3.5_2.13.1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Create Assembly
        run: sbt "clean;compile;assembly"